### ISSUE TITLE
adi_update_boot points to old releases

### ISSUE THREAD

**Issue by tfcollins** [analogdevicesinc/linux_image_ADI-scripts#10]

**Comment by rgetz** [comment]
http://swdownloads.analog.com/cse/fpga_sd/latest_boot.txt

still seems to point to 2017 release?

**Comment by mhennerich** [comment]
Yeah this is rather unmaintained. If we don't want to maintain this we should remove it.

**Comment by rgetz** [comment]
I will call you - hopefully there is someone we can assign to updating this.

**Comment by SRaus** [comment]
The script was updated to point to latest release.
