### ISSUE TITLE
pll_tx_sweep.sh

### ISSUE THREAD

**Issue by waseem-arshad94** [analogdevicesinc/linux_image_ADI-scripts#33]
My Question is about this script pll_tx_sweep.sh .
1- is it possible to create similar script for pll_rx sweep from 100MHz to 6 GHz ?
2 if answer to first one is yes then will it work in loopback (RF RX-RF TX )fashion ( referring to AXI_ad9361  if ADC path ( register 0x418 is set to 0x0 and DAC path register 0x418 set to 0x08 )

**Comment by mhennerich** [comment]
Of course you can sweep the LO over it's entire range.
Loopback and LO frequency control are not related, and work independent from each other.
